import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/styles/globals.css';
import Providers from '@/components/providers';
import Link from 'next/link';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="h-screen flex flex-col items-center pt-32 md:pt-52 pb-30">
            <div className="min-w-sm max-w-2xl px-5">
              <Link href="/">
                <h1 className="text-3xl font-semibold font-mono mb-4 hover:underline hover:underline-offset-4 p-6 bg-slate-200 rounded-xl">
                  Notehub
                </h1>
              </Link>
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
